name: Build MTP Battery Monitor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Build application
      run: |
        cl MTPBatteryMonitor.c /nologo /O2 /MT /W3 /DUNICODE /D_UNICODE /DWIN32_LEAN_AND_MEAN ^
           /Fe:MTPBatteryMonitor.exe /link PortableDeviceGUIDs.lib ole32.lib user32.lib gdi32.lib /SUBSYSTEM:WINDOWS
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MTPBatteryMonitor
        path: MTPBatteryMonitor.exe
